// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitle("TrainReservation")>]
[<assembly: AssemblyProduct("TrainReservation")>]
[<assembly: AssemblyVersion("0.1.0")>]
[<assembly: AssemblyMetadata("ReleaseDate", "2017-03-17T00:00:00.0000000")>]
[<assembly: AssemblyFileVersion("0.1.0")>]
[<assembly: AssemblyInformationalVersion("0.1.0")>]
[<assembly: AssemblyMetadata("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadata("GitHash", "b385af579477bb585016a6b5204121de4a485dac")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "TrainReservation"

    [<Literal>]
    let AssemblyProduct = "TrainReservation"

    [<Literal>]
    let AssemblyVersion = "0.1.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2017-03-17T00:00:00.0000000"

    [<Literal>]
    let AssemblyFileVersion = "0.1.0"

    [<Literal>]
    let AssemblyInformationalVersion = "0.1.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"

    [<Literal>]
    let AssemblyMetadata_GitHash =
        "b385af579477bb585016a6b5204121de4a485dac"
