// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitle("TrainReservation")>]
[<assembly: AssemblyProduct("TrainReservation")>]
[<assembly: AssemblyVersion("0.1.0")>]
[<assembly: AssemblyMetadata("ReleaseDate", "2020-02-28T12:00:00.0000000")>]
[<assembly: AssemblyFileVersion("0.1.0")>]
[<assembly: AssemblyInformationalVersion("0.1.0")>]
[<assembly: AssemblyMetadata("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadata("GitHash", "16fe5a31f19bc14ad208e4be71084b4ab89112b")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "TrainReservation"

    [<Literal>]
    let AssemblyProduct = "TrainReservation"

    [<Literal>]
    let AssemblyVersion = "0.1.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2020-02-28T12:00:00.0000000"

    [<Literal>]
    let AssemblyFileVersion = "0.1.0"

    [<Literal>]
    let AssemblyInformationalVersion = "0.1.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"

    [<Literal>]
    let AssemblyMetadata_GitHash =
        "16fe5a31f19bc14ad208e4be71084b4ab89112b"
